all:
  hosts:
    192.168.20.4:
  children:
    customer1:
      children:
        db:
          hosts:
            192.168.30.4:
            192.168.30.5:
        web:
          hosts:
            192.168.40.4:
            192.168.40.5:

