- hosts: web
  remote_user: root
  become: yes
  tasks:
  - name: Install Apache
    yum:
      name: httpd 
      state: installed
  - name: restart apache
    service:
      name: httpd
      state: reloaded

  - name: remove Apache
    yum:
      name: httpd
      state: removed